// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvpgochqebaxmlnwifli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2cGdvY2hxZWJheG1sbndpZmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzI4NDksImV4cCI6MjA3Mzc0ODg0OX0.uv5vTDfwaHbV8VWnPv4G5ghord0Ql_OV0MNX8cz60rk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});